name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: shufflewzc
          base: main
          head: main
